[project]
name = "web-analyzer"
version = "0.1.0"
description = "Analyze websites for best practices"
requires-python = "~=3.13"

[tool.ruff]
line-length = 100
target-version = "py313"
fix = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.pytest.ini_options]
pythonpath = ["/src"]
